BEGIN;

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "uuid" char(36) UNIQUE NOT NULL,
  "full_name" varchar(255),
  "user_name" varchar(255),
  "email" varchar(255) NOT NULL,
  "password_hash" varchar(60)
);

CREATE TABLE "payment_accounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "uuid" char(36) UNIQUE NOT NULL,
  "user_uuid" char(36) NOT NULL,
  "service_id" varchar(36) NOT NULL,
  "balance" bigint NOT NULL DEFAULT 0,
  "currency" varchar(24) NOT NULL
);

CREATE TABLE "transaction_histories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "uuid" char(36) UNIQUE NOT NULL,
  "account_uuid" char(36) NOT NULL,
  "dest_uuid" char(36),
  "mutation" bigint NOT NULL,
  "currency" varchar(24) NOT NULL,
  "status" smallint NOT NULL,
  "address" varchar(255),
  "transaction_note" varchar(512),
  "transaction_date" timestamp NOT NULL,
  "transaction_type" smallint NOT NULL
);

CREATE TABLE "recurring_payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "uuid" char(36) UNIQUE NOT NULL,
  "service_id" varchar(36) UNIQUE NOT NULL,
  "account_uuid" char(36) NOT NULL,
  "scheduler_type" smallint NOT NULL,
  "last_charge" timestamp
);

CREATE INDEX "idx_payment_accounts_service_id" ON "payment_accounts" ("service_id");
CREATE INDEX "idx_payment_accounts_user_uuid" ON "payment_accounts" ("user_uuid");

CREATE INDEX "idx_transaction_histories_account_uuid" ON "transaction_histories" ("account_uuid");
CREATE INDEX "idx_transaction_histories_dest_uuid" ON "transaction_histories" ("dest_uuid");
CREATE INDEX "idx_transaction_histories_status" ON "transaction_histories" ("status");
CREATE INDEX "idx_transaction_histories_transaction_type" ON "transaction_histories" ("transaction_type");

CREATE INDEX "idx_recurring_payments_service_id" ON "recurring_payments" ("service_id");
CREATE INDEX "idx_recurring_payments_account_uuid" ON "recurring_payments" ("account_uuid");
CREATE INDEX "idx_recurring_payments_scheduler_type" ON "recurring_payments" ("scheduler_type");

ALTER TABLE "payment_accounts" ADD FOREIGN KEY ("user_uuid") REFERENCES "users" ("uuid");
ALTER TABLE "transaction_histories" ADD FOREIGN KEY ("account_uuid") REFERENCES "payment_accounts" ("uuid");
ALTER TABLE "transaction_histories" ADD FOREIGN KEY ("dest_uuid") REFERENCES "payment_accounts" ("uuid");
ALTER TABLE "recurring_payments" ADD FOREIGN KEY ("account_uuid") REFERENCES "payment_accounts" ("uuid");

COMMIT;