BEGIN;

ALTER TABLE "payment_accounts" DROP CONSTRAINT IF EXISTS "payment_accounts_user_uuid_fkey";
ALTER TABLE "transaction_histories" DROP CONSTRAINT IF EXISTS "transaction_histories_account_uuid_fkey";
ALTER TABLE "transaction_histories" DROP CONSTRAINT IF EXISTS "transaction_histories_dest_uuid_fkey";
ALTER TABLE "recurring_payments" DROP CONSTRAINT IF EXISTS "recurring_payments_account_uuid_fkey";

ALTER TABLE "users" ADD COLUMN "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL;
ALTER TABLE "payment_accounts" ADD COLUMN "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL;
ALTER TABLE "transaction_histories" ADD COLUMN "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL;
ALTER TABLE "recurring_payments" ADD COLUMN "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL;

ALTER TABLE "users" ALTER COLUMN "uuid" TYPE CHAR(36) USING "uuid"::CHAR(36);
ALTER TABLE "users" ALTER COLUMN "uuid" DROP DEFAULT;

ALTER TABLE "payment_accounts" ALTER COLUMN "uuid" TYPE CHAR(36) USING "uuid"::CHAR(36);
ALTER TABLE "payment_accounts" ALTER COLUMN "uuid" DROP DEFAULT;
ALTER TABLE "payment_accounts" ALTER COLUMN "user_uuid" TYPE CHAR(36) USING "user_uuid"::CHAR(36);

ALTER TABLE "transaction_histories" ALTER COLUMN "uuid" TYPE CHAR(36) USING "uuid"::CHAR(36);
ALTER TABLE "transaction_histories" ALTER COLUMN "uuid" DROP DEFAULT;
ALTER TABLE "transaction_histories" ALTER COLUMN "account_uuid" TYPE CHAR(36) USING "account_uuid"::CHAR(36);
ALTER TABLE "transaction_histories" ALTER COLUMN "dest_uuid" TYPE CHAR(36) USING "dest_uuid"::CHAR(36);

ALTER TABLE "recurring_payments" ALTER COLUMN "uuid" TYPE CHAR(36) USING "uuid"::CHAR(36);
ALTER TABLE "recurring_payments" ALTER COLUMN "uuid" DROP DEFAULT;
ALTER TABLE "recurring_payments" ALTER COLUMN "account_uuid" TYPE CHAR(36) USING "account_uuid"::CHAR(36);

ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_primary_key";
ALTER TABLE "payment_accounts" DROP CONSTRAINT IF EXISTS "payment_accounts_primary_key";
ALTER TABLE "transaction_histories" DROP CONSTRAINT IF EXISTS "transaction_histories_primary_key";
ALTER TABLE "recurring_payments" DROP CONSTRAINT IF EXISTS "recurring_payments_primary_key";

ALTER TABLE "payment_accounts" ADD CONSTRAINT "payment_accounts_user_uuid_fkey" FOREIGN KEY ("user_uuid") REFERENCES "users" ("uuid");
ALTER TABLE "transaction_histories" ADD CONSTRAINT "transaction_histories_account_uuid_fkey" FOREIGN KEY ("account_uuid") REFERENCES "payment_accounts" ("uuid");
ALTER TABLE "transaction_histories" ADD CONSTRAINT "transaction_histories_dest_uuid_fkey" FOREIGN KEY ("dest_uuid") REFERENCES "payment_accounts" ("uuid");
ALTER TABLE "recurring_payments" ADD CONSTRAINT "recurring_payments_account_uuid_fkey" FOREIGN KEY ("account_uuid") REFERENCES "payment_accounts" ("uuid");
COMMIT;