BEGIN;

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "uuid" char(36) UNIQUE NOT NULL,
  "full_name" varchar(255),
  "user_name" varchar(255),
  "password_hash" varchar(60)
);

CREATE TABLE "monetary_accounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "uuid" char(36) UNIQUE NOT NULL,
  "user_uuid" char(36),
  "service_id" varchar(36),
  "balance" bigint,
  "currency" varchar(24)
);

CREATE TABLE "transaction_histories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "uuid" char(36) UNIQUE NOT NULL,
  "user_uuid" char(36),
  "service_id" varchar(36),
  "mutation" bigint,
  "currency" varchar(24),
  "status" smallint,
  "address" varchar(255),
  "transaction_note" varchar(512)
);

CREATE TABLE "recurring_payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "service_id" varchar(36) UNIQUE NOT NULL,
  "account_uuid" char(36),
  "scheduler_type" smallint,
  "last_charge" timestamp
);

CREATE INDEX "idx_monetary_accounts_service_id" ON "monetary_accounts" ("service_id");
CREATE INDEX "idx_monetary_accounts_user_uuid" ON "monetary_accounts" ("user_uuid");

CREATE INDEX "idx_transaction_histories_service_id" ON "transaction_histories" ("service_id");
CREATE INDEX "idx_transaction_histories_user_uuid" ON "transaction_histories" ("user_uuid");
CREATE INDEX "idx_transaction_histories_status" ON "transaction_histories" ("status");

CREATE INDEX "idx_recurring_payments_service_id" ON "recurring_payments" ("service_id");
CREATE INDEX "idx_recurring_payments_account_uuid" ON "recurring_payments" ("account_uuid");
CREATE INDEX "idx_recurring_payments_scheduler_type" ON "recurring_payments" ("scheduler_type");

ALTER TABLE "monetary_accounts" ADD FOREIGN KEY ("user_uuid") REFERENCES "users" ("uuid");
ALTER TABLE "transaction_histories" ADD FOREIGN KEY ("user_uuid") REFERENCES "users" ("uuid");
ALTER TABLE "recurring_payments" ADD FOREIGN KEY ("account_uuid") REFERENCES "monetary_accounts" ("uuid");

COMMIT;