services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mock_fintech
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@concreteai.io
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    ports:
      - 7777:80
  migration:
    build:
      context: .
    command: migrate -database ${POSTGRESQL_URL} -path db/migrations up
    env_file:
      - ./.env
  user:
    build:
      context: .
    command: "user"
    env_file:
      - ./.env
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - migration
  payment:
    build:
      context: .
    command: "payment"
    env_file:
      - ./.env
    ports:
      - 8081:8081
    depends_on:
      - postgres
      - migration
