//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type RecurringPayments struct {
	ID            int32
	UUID          string
	ServiceID     string
	AccountUUID   string
	SchedulerType int16
	LastCharge    *time.Time
}
