//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type TransactionHistories struct {
	UUID            uuid.UUID `sql:"primary_key"`
	AccountUUID     uuid.UUID
	DestUUID        *uuid.UUID
	Mutation        int64
	Currency        string
	Status          int16
	Address         *string
	TransactionNote *string
	TransactionDate time.Time
	TransactionType int16
}
