basePath: /
consumes:
- application/json
- multipart/form-data
- application/x-www-form-urlencoded
definitions:
  payment.SendPayload:
    properties:
      account:
        type: string
      amount:
        maximum: 999999999999999
        minimum: 1
        type: integer
      dest:
        type: string
    required:
    - account
    - amount
    - dest
    type: object
  payment.SendResponse:
    properties:
      transaction:
        $ref: '#/definitions/platform.TransactionHistory'
    type: object
  payment.SubscribePayload:
    properties:
      account:
        type: string
      billing:
        type: string
      callback_data:
        type: string
      service:
        type: string
    required:
    - account
    - billing
    - callback_data
    - service
    type: object
  payment.SubscribeResponse:
    properties:
      payment:
        $ref: '#/definitions/platform.RecurringPayment'
      transaction:
        $ref: '#/definitions/platform.TransactionHistory'
    type: object
  payment.UnsubscribePayload:
    properties:
      payment_id:
        type: string
    required:
    - payment_id
    type: object
  payment.UnsubscribeResponse:
    properties:
      status:
        type: string
      transaction:
        $ref: '#/definitions/platform.TransactionHistory'
    type: object
  payment.WithdrawPayload:
    properties:
      account_id:
        type: string
      amount:
        maximum: 999999999999999
        minimum: 1
        type: integer
      callback:
        type: string
    required:
    - account_id
    - amount
    - callback
    type: object
  payment.WithdrawResponse:
    properties:
      transaction:
        $ref: '#/definitions/platform.TransactionHistory'
    type: object
  platform.RecurringPayment:
    properties:
      accountUUID:
        type: string
      chargingMethod:
        type: integer
      foreignID:
        type: string
      lastCharge:
        type: string
      schedulerType:
        type: integer
      serviceID:
        type: string
      uuid:
        type: string
    type: object
  platform.TransactionHistory:
    properties:
      accountUUID:
        type: string
      address:
        type: string
      currency:
        type: string
      destUUID:
        type: string
      issuerUUID:
        type: string
      mutation:
        type: integer
      serviceID:
        type: string
      status:
        type: integer
      transactionDate:
        type: string
      transactionNote:
        type: string
      transactionType:
        type: integer
      userUUID:
        type: string
      uuid:
        type: string
    type: object
info:
  contact:
    name: Aiman Fauzy
  title: Payment Manager Service
paths:
  /send:
    post:
      parameters:
      - description: Send payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/payment.SendPayload'
      - description: Authentication token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payment.SendResponse'
        default:
          description: ""
          schema:
            type: string
      summary: Send amount to account UUID
  /subscribe:
    post:
      parameters:
      - description: Subscribe payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/payment.SubscribePayload'
      - description: Authentication token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/payment.SubscribeResponse'
        default:
          description: ""
          schema:
            type: string
      summary: Subscribe to recurring payment
  /unsubscribe:
    post:
      parameters:
      - description: Unsubscribe payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/payment.UnsubscribePayload'
      - description: Authentication token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payment.UnsubscribeResponse'
        default:
          description: ""
          schema:
            type: string
      summary: Unsubscribe to recurring payment
  /withdraw:
    post:
      parameters:
      - description: Withdraw payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/payment.WithdrawPayload'
      - description: Authentication token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payment.WithdrawResponse'
        default:
          description: ""
          schema:
            type: string
      summary: Withdraw amount from account
swagger: "2.0"
